### ISSUE TITLE
Bibliotheken für Clientseite für eigenen Server 

### ISSUE THREAD

**Issue by phuef** [Delucse/GeosoftwareProject#14]

**Comment by Delucse** [comment]
minfizierte Bibliotheken gibt es für folgende Bibliotheken nicht:

-  /leaflet/leaflet.css
-  /leaflet-control-geocoder/Control.Geocoder.css
-  /leaflet-routing-machine/leaflet-routing-machine.css
-  /leaflet/leaflet.js"
