### ISSUE TITLE
Abfragen und speichern der Daten der Movebank API

### ISSUE THREAD

**Issue by phuef** [Delucse/GeosoftwareProject#5]

**Comment by Delucse** [comment]
bisher davon ausgegangen, das die minimalen Anforderungen für eine korrekte Abfrage mindestens die study_id, den taxicol_..._name und den sensor_type beinhalten müssen. Allerdings reicht es auch aus nur die study_id und den sensor-type anzugeben!

**Comment by Delucse** [comment]
erfolgreiche Erweiterung der Funktionalität (Abfrage und Update der Daten nun möglich)

TODO: kleinen Text zu movebank.org ergänzen

**Comment by Delucse** [comment]
Text ergänzt
