### ISSUE TITLE
Funktionalität in allen gängigen Browsern

### ISSUE THREAD

**Issue by phuef** [Delucse/GeosoftwareProject#8]
Chrome, Firefox, (Safari)

**Comment by Delucse** [comment]
damit das Abrufen der Movebank API in allen gängigen Browsern möglich ist und gleichzeitig der Cursor verändert werden kann, muss nochmals die submit() - Funktion ausgeführt werden.

**Comment by phuef** [comment]
Funktioniert jetzt auch in Edge

**Comment by Delucse** [comment]
Funktionalitäten in
- Firefox
- Chrome
- Opera
- Microsoft Edge
gegeben
